### ISSUE TITLE
Adjusting the DBeaver installation

### ISSUE THREAD

**Issue by danielso2007** [danielso2007/development_installation_script#1]
- Modifying the installation of Dbeaver to use the repository and APT.

**Comment by denissoliveira** [comment]
Não entendi

Em sex, 13 de mar de 2020 12:29, Daniel Oliveira <notifications@github.com>
escreveu:

**Comment by danielso2007** [comment]
@denissoliveira Olha o commit que você vai entender. A instalação não é via arquivo, e sim, via repositório usando APT-GET.
